version: '3'
services:
  supply-service:
    build:
      context: ./supply
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 3306:3306
    restart: always
    environment:
      - DB_HOST=192.168.87.87
      - DB_PORT=3306
    depends_on:
      - db

  demand-service:
    build:
      context: ./demand
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - db

  auction-service:
    build:
      context: ./auction
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=ad_auction
      - DB_HOST=192.168.87.87
      - DB_PORT=3306
    ports:
      - 3306:3306